### ISSUE TITLE
Translate died

### ISSUE THREAD

**Issue by TheSuperGamer20578** [TheSuperGamer20578/Sudan-bot#158]
Translate died

# Steps To Reproduce
1. Use translate

# Expected behaviour

It works

# Screenshots

![SmartSelect_20210210-155451_Chrome.jpg](https://user-images.githubusercontent.com/30369708/107467480-3576cf80-6bba-11eb-9c87-18b764900f84.jpg)

# Additional context

**Comment by ogxn** [comment]
Try using the Google Translate API

**Comment by TheSuperGamer20578** [comment]
> Try using the Google Translate API

Dont you have to pay for that?

**Comment by ogxn** [comment]
> > Try using the Google Translate API
> 
> Dont you have to pay for that?

Yeah... One problem you've mentioned with using GCP is that it requires cc for the 1-year $200 credit.

DeepL API is €5/mo

**Comment by TheSuperGamer20578** [comment]
> > > Try using the Google Translate API
> > 
> > Dont you have to pay for that?
> 
> Yeah... One problem you've mentioned with using GCP is that it requires cc for the 1-year $200 credit.
> 
> DeepL API is €5/mo

Unless you use one of the non functioning python library's that do it for free

Only problem: last time I checked they didn't work, I might look again one day

**Comment by TheSuperGamer20578** [comment]
translate library `googletrans` is still busted
![image](https://user-images.githubusercontent.com/30369708/109409709-1d3fe680-79e9-11eb-91a9-df4f162ce65f.png)
